version: '3'
services: 
  web: 
    build: ./frontend
    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/frontend

  api: 
    build: ./backend
    ports:
      - "8000:8000"

    volumes: 
    - ./backend:/backend

    
    env_file: 
      - ./backend/backend/.env
